#!/usr/bin/env node
/*
 * step9a_translation_infrastructure.cjs
 * =====================================
 * Sets up the translation merge pipeline.
 *
 * 1. Creates src/data/legal/translations/ directory
 * 2. Replaces src/data/legal/index.js with a version that auto-loads and
 *    merges any *.js file in translations/ into the entries at runtime
 * 3. Patches scripts/prerender-legal.cjs to do the same merge at build time
 *
 * After this runs, dropping a file like src/data/legal/translations/es.js
 * with shape `{ "entry-id": { title, summary, yourRights }, ... }` will
 * automatically populate entry.title.es, entry.summary.es, etc. both in
 * the React app AND in the pre-rendered HTML.
 *
 * Safety: backups written with .bak9a extension.
 */

const fs = require('fs');
const os = require('os');
const path = require('path');

const HOME = os.homedir();
const ROOT = path.join(HOME, 'roc-help-finder');
const LEGAL_DIR = path.join(ROOT, 'src', 'data', 'legal');
const TRANSLATIONS_DIR = path.join(LEGAL_DIR, 'translations');
const INDEX_JS = path.join(LEGAL_DIR, 'index.js');
const PRERENDER = path.join(ROOT, 'scripts', 'prerender-legal.cjs');

// ── Step 1: Create translations/ directory with a README placeholder ─────
fs.mkdirSync(TRANSLATIONS_DIR, { recursive: true });
console.log(`✓ Ensured ${TRANSLATIONS_DIR}`);

const readmePath = path.join(TRANSLATIONS_DIR, 'README.md');
if (!fs.existsSync(readmePath)) {
  fs.writeFileSync(
    readmePath,
    `# Legal Library Translations

This folder holds per-language translation files for the legal library.
One file per language, using the language code as filename:

  es.js   Spanish
  vi.js   Vietnamese
  zh.js   Chinese
  ... etc.

Each file exports a default object keyed by entry ID:

    export default {
      "benefit-overpayment-ny": {
        title: "...",
        summary: "...",
        yourRights: ["...", "...", "..."]
      },
      // ... more entries
    }

These are merged into the entries at load time (index.js) and at build
time (scripts/prerender-legal.cjs). The merge overwrites only fields
that are present in the translation file — untranslated fields fall
back to English.

Translations are AI-generated and should receive a native-speaker review
pass before being considered certified for legal use.
`,
    'utf8'
  );
  console.log(`✓ Wrote README.md`);
}

// ── Step 2: New index.js with merge logic ─────────────────────────────────
const newIndexJs = `// AUTO-GENERATED by step1_import_legal_entries.cjs + step9a
// Do NOT edit by hand. Re-run the generator scripts if needed.
//
// Vite's import.meta.glob auto-imports every file in ./entries/ and
// ./translations/ at build time. Translation files are merged into the
// entries so that entry.title.es, entry.summary.es, etc. are populated
// transparently.

const entryModules = import.meta.glob('./entries/*.js', { eager: true });
const translationModules = import.meta.glob('./translations/*.js', { eager: true });

// Translatable fields — match the fields generated by LGLW.
const TRANSLATABLE_STRING_FIELDS = ['title', 'summary', 'whatItMeans', 'example'];
const TRANSLATABLE_ARRAY_FIELDS = ['whoQualifies', 'yourRights', 'legalOptions'];

// Build translation map: { es: { "entry-id": {...} }, vi: {...}, ... }
const translations = {};
for (const [p, mod] of Object.entries(translationModules)) {
  const match = p.match(/\\/translations\\/([a-z-]+)\\.js$/i);
  if (!match) continue;
  const lang = match[1];
  translations[lang] = (mod && mod.default) || mod || {};
}

// Load entries
const rawEntries = Object.values(entryModules)
  .map((mod) => Object.values(mod)[0])
  .filter(Boolean);

// Merge translations into each entry in place
for (const entry of rawEntries) {
  if (!entry || !entry.id) continue;
  for (const [lang, langData] of Object.entries(translations)) {
    const t = langData && langData[entry.id];
    if (!t) continue;
    for (const f of TRANSLATABLE_STRING_FIELDS) {
      if (t[f] && entry[f] && typeof entry[f] === 'object') {
        entry[f][lang] = t[f];
      }
    }
    for (const f of TRANSLATABLE_ARRAY_FIELDS) {
      if (Array.isArray(t[f]) && entry[f] && typeof entry[f] === 'object') {
        entry[f][lang] = t[f];
      }
    }
  }
}

export const LEGAL_ENTRIES = rawEntries.sort((a, b) => {
  const catCmp = (a.category || '').localeCompare(b.category || '');
  if (catCmp !== 0) return catCmp;
  return (a.title?.en || '').localeCompare(b.title?.en || '');
});

export const LEGAL_ENTRIES_BY_ID = Object.fromEntries(
  LEGAL_ENTRIES.map((e) => [e.id, e])
);

export const LEGAL_ENTRIES_BY_CATEGORY = LEGAL_ENTRIES.reduce((acc, e) => {
  const cat = e.category || 'other';
  (acc[cat] = acc[cat] || []).push(e);
  return acc;
}, {});

export const LEGAL_CATEGORIES = Object.keys(LEGAL_ENTRIES_BY_CATEGORY).sort();

export const TRANSLATED_LANGUAGES = Object.keys(translations).sort();
`;

if (fs.existsSync(INDEX_JS)) {
  fs.writeFileSync(INDEX_JS + '.bak9a', fs.readFileSync(INDEX_JS, 'utf8'), 'utf8');
  console.log(`✓ Backed up ${INDEX_JS} → .bak9a`);
}
fs.writeFileSync(INDEX_JS, newIndexJs, 'utf8');
console.log(`✓ Wrote new ${INDEX_JS}`);

// ── Step 3: Patch scripts/prerender-legal.cjs ─────────────────────────────
if (!fs.existsSync(PRERENDER)) {
  console.error(`ERROR: ${PRERENDER} not found.`);
  process.exit(1);
}
let prerenderContent = fs.readFileSync(PRERENDER, 'utf8');

if (prerenderContent.includes('loadTranslations')) {
  console.log('✓ prerender-legal.cjs already has loadTranslations — skipping patch');
} else {
  const markerA = `async function loadEntries() {`;
  if (!prerenderContent.includes(markerA)) {
    console.error('ERROR: loadEntries marker not found in prerender-legal.cjs');
    process.exit(1);
  }

  const loadTranslationsFn =
`async function loadTranslations() {
  const dir = path.join(ROOT, 'src', 'data', 'legal', 'translations');
  if (!fs.existsSync(dir)) return {};
  const files = fs.readdirSync(dir).filter((f) => f.endsWith('.js'));
  const out = {};
  for (const f of files) {
    const lang = path.basename(f, '.js');
    const abs = path.join(dir, f);
    const mod = await import(pathToFileURL(abs).href);
    out[lang] = (mod && mod.default) || mod || {};
  }
  return out;
}

function applyTranslations(entries, translations) {
  const STRING_FIELDS = ['title', 'summary', 'whatItMeans', 'example'];
  const ARRAY_FIELDS = ['whoQualifies', 'yourRights', 'legalOptions'];
  for (const entry of entries) {
    if (!entry || !entry.id) continue;
    for (const lang of Object.keys(translations)) {
      const t = translations[lang] && translations[lang][entry.id];
      if (!t) continue;
      for (const f of STRING_FIELDS) {
        if (t[f] && entry[f] && typeof entry[f] === 'object') {
          entry[f][lang] = t[f];
        }
      }
      for (const f of ARRAY_FIELDS) {
        if (Array.isArray(t[f]) && entry[f] && typeof entry[f] === 'object') {
          entry[f][lang] = t[f];
        }
      }
    }
  }
}

`;

  prerenderContent = prerenderContent.replace(markerA, loadTranslationsFn + markerA);
  console.log('✓ Inserted loadTranslations + applyTranslations before loadEntries');

  // Hook into main() — after "const entries = await loadEntries();"
  const markerB = `const entries = await loadEntries();
  console.log('✓ Loaded ' + entries.length + ' entries');`;
  const replaceB =
`const entries = await loadEntries();
  console.log('✓ Loaded ' + entries.length + ' entries');

  const translations = await loadTranslations();
  const translatedLangs = Object.keys(translations);
  if (translatedLangs.length > 0) {
    applyTranslations(entries, translations);
    console.log('✓ Merged translations for: ' + translatedLangs.join(', '));
  } else {
    console.log('ℹ No translation files yet — all languages fall back to English');
  }`;

  if (!prerenderContent.includes(markerB)) {
    console.error('ERROR: loadEntries call marker not found in main()');
    process.exit(1);
  }
  prerenderContent = prerenderContent.replace(markerB, replaceB);
  console.log('✓ Hooked applyTranslations into main()');

  fs.writeFileSync(PRERENDER + '.bak9a', fs.readFileSync(PRERENDER, 'utf8'), 'utf8');
  console.log(`✓ Backup saved: ${PRERENDER}.bak9a`);
  fs.writeFileSync(PRERENDER, prerenderContent, 'utf8');
  console.log(`✓ Patched ${PRERENDER}`);
}

console.log();
console.log('Step 9a complete. Translation infrastructure ready.');
console.log('Next: load entry files in batches so I can generate translation content.');
