import React from "react";
// AUTO-GENERATED by step8a_category_tiles.cjs
// Legal Library: category overview + filtered browse + entry detail.
//
// Exported components:
//   LegalLibraryCategories — top-level category tile overview (7 tiles)
//   LegalLibraryBrowse     — entries filtered to one category
//   LegalLibraryEntry      — detail view for a single entry

import { LEGAL_ENTRIES, LEGAL_ENTRIES_BY_ID, LEGAL_ENTRIES_BY_CATEGORY, LEGAL_CATEGORIES } from "../data/legal";
import { GLOSSARY_TERMS_BY_CATEGORY } from "../data/legal/glossary-index";
import GlossaryText from "./GlossaryTooltip";
import { LEGAL_LANGS, RTL_LEGAL_LANGS } from "../data/legal/langs";

const C = {
  forest: "#2e7d32", leaf: "#43a047", sage: "#e8f5e9",
  warmBg: "#fafaf7", cream: "#f5f0e8", bark: "#1a1a1a",
  stone: "#555", dust: "#767676", amber: "#d4a056",
  amberLight: "#fdf6ec", white: "#fff", border: "#e8e4dc",
};

const SERIF = "'DM Serif Display', Georgia, serif";

const AUTHORITY_META = {
  "state-statute": {
    label: "NY State Statute",
    caption: "This rule comes from a law passed by the New York State Legislature.",
    color: "#1565c0",
    bg: "#e3f2fd",
    border: "#bbdefb",
  },
  "federal-statute": {
    label: "Federal Statute",
    caption: "This rule comes from a law passed by Congress. It applies nationwide.",
    color: "#4527a0",
    bg: "#ede7f6",
    border: "#d1c4e9",
  },
  "state-regulation": {
    label: "NY Regulation",
    caption: "This rule comes from a state agency regulation, adopted under a state statute.",
    color: "#00695c",
    bg: "#e0f2f1",
    border: "#b2dfdb",
  },
  "federal-regulation": {
    label: "Federal Regulation",
    caption: "This rule comes from a federal agency regulation, adopted under a federal statute.",
    color: "#6a1b9a",
    bg: "#f3e5f5",
    border: "#e1bee7",
  },
  "local-ordinance": {
    label: "Local Ordinance",
    caption: "This rule is set by a town, village, or city — not state law. Rules differ between municipalities.",
    color: "#bf360c",
    bg: "#fbe9e7",
    border: "#ffccbc",
  },
  "common-law": {
    label: "Court-Made Law",
    caption: "This rule comes from court decisions, not a statute. Rules can shift as new cases are decided.",
    color: "#6d4c41",
    bg: "#efebe9",
    border: "#d7ccc8",
  },
  "agency-program": {
    label: "Agency Program",
    caption: "This describes how a government program works. Procedures are set by the agency running it.",
    color: "#2e7d32",
    bg: "#e8f5e9",
    border: "#c8e6c9",
  },
};

const NY_CODE_NAMES = {
  RPP: "Real Property Law", RPA: "Real Property Actions and Proceedings Law",
  RPT: "Real Property Tax Law", GBS: "General Business Law",
  GOB: "General Obligations Law", PBH: "Public Health Law",
  PBS: "Public Service Law", LAB: "Labor Law", PEN: "Penal Law",
  VAT: "Vehicle and Traffic Law", TAX: "Tax Law", ELD: "Elder Law",
  EDN: "Education Law", EXC: "Executive Law", DOM: "Domestic Relations Law",
  DRL: "Domestic Relations Law", CVP: "Civil Practice Law and Rules",
  CPL: "Criminal Procedure Law", EPT: "Estates, Powers and Trusts Law",
  SOS: "Social Services Law", ISC: "Insurance Law", MHY: "Mental Hygiene Law",
  GMU: "General Municipal Law", TWN: "Town Law", VIL: "Village Law",
  GCT: "General City Law", ELN: "Election Law", LIE: "Lien Law",
  AGM: "Agriculture and Markets Law", PPL: "Personal Property Law",
  SCP: "Surrogate's Court Procedure Act", NAV: "Navigation Law",
  ENV: "Environmental Conservation Law", BNK: "Banking Law",
  CAN: "Cannabis Law", CNB: "Cannabis Law", ABP: "Abandoned Property Law",
  FCT: "Family Court Act", JUD: "Judiciary Law", COR: "Correction Law",
  CVR: "Civil Rights Law", CVS: "Civil Service Law",
  UCC: "Uniform Commercial Code", WKC: "Workers' Compensation Law",
  MDW: "Multiple Dwelling Law", MIL: "Military Law",
  NPC: "Not-for-Profit Corporation Law", PBO: "Public Officers Law",
};

function parseSource(url) {
  try {
    const u = new URL(url);
    // NY statute: nysenate.gov/legislation/laws/XXX/YYY
    let m = url.match(/nysenate\.gov\/legislation\/laws\/([A-Z]+)(?:\/([A-Z0-9.-]+))?/i);
    if (m) {
      const code = m[1].toUpperCase();
      const section = m[2];
      const codeName = NY_CODE_NAMES[code] || (code + " (NY)");
      if (!section) return { label: "NY " + codeName, url, host: u.hostname };
      const isArticle = /^A[0-9]/i.test(section);
      const label = "NY " + codeName + (isArticle ? " Article " + section.slice(1) : " § " + section.toLowerCase());
      return { label, url, host: u.hostname };
    }
    // US code: law.cornell.edu/uscode/text/N/MMM
    m = url.match(/law\.cornell\.edu\/uscode\/text\/(\d+)\/([A-Za-z0-9-]+)/);
    if (m) return { label: m[1] + " U.S.C. § " + m[2], url, host: u.hostname };
    // Chapter: law.cornell.edu/uscode/text/N/chapter-K
    m = url.match(/law\.cornell\.edu\/uscode\/text\/(\d+)\/chapter-(\d+)/);
    if (m) return { label: m[1] + " U.S.C. Chapter " + m[2], url, host: u.hostname };
    // CFR: law.cornell.edu/cfr/text/N/part-M or /N/NN.NN
    m = url.match(/law\.cornell\.edu\/cfr\/text\/(\d+)\/part-([A-Za-z0-9-]+)(?:\/subpart-([A-Za-z]+))?/);
    if (m) {
      let label = m[1] + " C.F.R. Part " + m[2];
      if (m[3]) label += " Subpart " + m[3].toUpperCase();
      return { label, url, host: u.hostname };
    }
    m = url.match(/law\.cornell\.edu\/cfr\/text\/(\d+)\/([0-9.]+)/);
    if (m) return { label: m[1] + " C.F.R. § " + m[2], url, host: u.hostname };
    // NYCRR: law.cornell.edu/regulations/new-york/title-N/...appendix-XX-X
    m = url.match(/law\.cornell\.edu\/regulations\/new-york\/title-(\d+).*appendix-([0-9-A-Za-z]+)/);
    if (m) return { label: m[1] + " NYCRR Appendix " + m[2], url, host: u.hostname };
    m = url.match(/law\.cornell\.edu\/regulations\/new-york\/title-(\d+).*part-([0-9-]+)(?:\/subpart-([0-9-]+))?/);
    if (m) {
      let label = m[1] + " NYCRR Part " + m[2];
      if (m[3]) label += " Subpart " + m[3];
      return { label, url, host: u.hostname };
    }
    // UCC: law.cornell.edu/ucc/N/N-NNN
    m = url.match(/law\.cornell\.edu\/ucc\/(\d+)\/(\d+-\d+)/);
    if (m) return { label: "UCC § " + m[2], url, host: u.hostname };
    // Constitution
    m = url.match(/law\.cornell\.edu\/constitution\/([a-z_]+)/);
    if (m) return { label: "U.S. Constitution — " + m[1].replace(/_/g, " "), url, host: u.hostname };
    // Fallback: just use hostname as label
    return { label: u.hostname, url, host: u.hostname };
  } catch (e) {
    return { label: url, url, host: "" };
  }
}

function VerifiedBadge({ lastVerified }) {
  if (!lastVerified) return null;
  const d = new Date(lastVerified + "T00:00:00");
  if (isNaN(d.getTime())) return null;
  const pretty = d.toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" });
  return (
    <div style={{
      display: "flex",
      flexWrap: "wrap",
      alignItems: "center",
      gap: 8,
      margin: "14px 0 10px",
      padding: "10px 14px",
      background: "#e8f5e9",
      border: "1px solid #66bb6a",
      borderRadius: 8,
      fontSize: 13,
      color: "#1b5e20",
    }}>
      <span style={{ fontSize: 16, fontWeight: 700 }}>✓</span>
      <span style={{ fontWeight: 600 }}>Verified {pretty}</span>
      <span style={{ fontSize: 11, color: "#2e7d32", flexBasis: "100%", lineHeight: 1.45 }}>
        Phones and links are checked on a regular schedule. Fee amounts and program details may change — click the official source for current rates.
      </span>
    </div>
  );
}

function AuthorityBadge({ authorityType }) {
  if (!authorityType) return null;
  const meta = AUTHORITY_META[authorityType];
  if (!meta) return null;
  return (
    <div style={{
      marginBottom: 20,
      padding: "10px 14px",
      background: meta.bg,
      border: "1px solid " + meta.border,
      borderRadius: 10,
      fontSize: 13,
      lineHeight: 1.5,
    }}>
      <span style={{ fontWeight: 700, color: meta.color, marginRight: 8 }}>
        {meta.label}
      </span>
      <span style={{ color: "#555" }}>{meta.caption}</span>
    </div>
  );
}

// Category metadata — icons, labels, and short descriptions for the tiles
export const CATEGORY_META = {
  benefits: {
    icon: "💰",
    label: "Money & Benefits",
    desc: "SNAP, Medicaid, Medicare, cash help, disability, fair hearings, appeals.",
  },
  consumer: {
    icon: "🛒",
    label: "Debt & Money Problems",
    desc: "Debt collection, scams, contracts, refunds, unfair charges.",
  },
  housing: {
    icon: "🏠",
    label: "Housing & Rent",
    desc: "Landlord disputes, eviction, security deposits, housing discrimination.",
  },
  family: {
    icon: "👨‍👩‍👧",
    label: "Family Decisions",
    desc: "Child care, custody, planning ahead with Power of Attorney or Health Care Proxy, guardianship alternatives.",
  },
  employment: {
    icon: "💼",
    label: "Work & Pay",
    desc: "Wage theft, unpaid wages, overtime, wrongful firing, workplace rights.",
  },
  vehicle: {
    icon: "🚗",
    label: "Driving & Tickets",
    desc: "Driver's license, suspensions, registration, tickets, DWI.",
  },
  criminal: {
    icon: "⚖️",
    label: "Arrests & Records",
    desc: "Rights when arrested, drug charges, Good Samaritan Law, sealing or expunging a record.",
  },
  trades: {
    icon: "🔨",
    label: "Home Projects & Permits",
    desc: "Building permits, contractor rules, and local ordinances for roofing, plumbing, electrical, and HVAC work.",
  },
};

function pickText(field, lang) {
  if (!field) return "";
  return field[lang] || field.en || "";
}
function pickArr(field, lang) {
  if (!field) return [];
  return field[lang] || field.en || [];
}

// Languages where at least one legal entry has a real translation. Computed
// from the merged entry data so the list grows automatically as new per-entry
// translations are added. Used as the category/library fallback.
const SITE_TRANSLATED_LANGS = (() => {
  const codes = new Set(["en"]);
  for (const e of LEGAL_ENTRIES) {
    if (e && e.title) for (const k of Object.keys(e.title)) codes.add(k);
  }
  return LEGAL_LANGS.filter((l) => codes.has(l.code));
})();

// For an entry page, the picker should only offer languages where THIS entry
// has a real translation. English is always included.
function availableLangsForEntry(entry) {
  const codes = new Set(["en"]);
  if (entry && entry.title) for (const k of Object.keys(entry.title)) codes.add(k);
  return LEGAL_LANGS.filter((l) => codes.has(l.code));
}

// LanguagePicker removed per maintainer policy 2026-04-26: translations
// outside English are gated on native-speaker review and not yet in
// production. Hiding the picker prevents implying coverage we don't have.
// Re-add when reviewed translations are ready to ship.
function LanguagePicker() { return null; }

// ═══════════════════════════════════════════════════════════════════════════
// CATEGORY OVERVIEW — 7 big tiles
// ═══════════════════════════════════════════════════════════════════════════
export function LegalLibraryCategories({ legalLang, setLegalLang, onOpenCategory, onOpenEntry, onBack }) {
  const isRTL = RTL_LEGAL_LANGS.has(legalLang);
  // Only show categories that actually have entries
  const categories = LEGAL_CATEGORIES.filter((c) => (LEGAL_ENTRIES_BY_CATEGORY[c] || []).length > 0);

  // Search across every entry in the library — title, summary, and tags.
  const [query, setQuery] = React.useState("");
  const trimmedQuery = query.trim().toLowerCase();
  const searchResults = React.useMemo(() => {
    if (trimmedQuery.length < 2) return [];
    return LEGAL_ENTRIES.filter((e) => {
      const title = (pickText(e.title, legalLang) || "").toLowerCase();
      const summary = (pickText(e.summary, legalLang) || "").toLowerCase();
      const tags = (e.tags || []).join(" ").toLowerCase();
      return title.includes(trimmedQuery) || summary.includes(trimmedQuery) || tags.includes(trimmedQuery);
    }).slice(0, 40);
  }, [trimmedQuery, legalLang]);

  return (
    <main dir={isRTL ? "rtl" : "ltr"} style={{ padding: "0 20px 40px", maxWidth: 920, margin: "0 auto" }}>
      <button onClick={onBack} style={{ background: "none", border: "none", cursor: "pointer", fontSize: 14, color: C.stone, padding: "16px 0", fontFamily: "inherit" }}>← Back</button>

      <h1 style={{ fontFamily: SERIF, fontSize: 36, fontWeight: 400, marginBottom: 6, color: C.bark, lineHeight: 1.2 }}>Know Your Rights</h1>
      <p style={{ fontSize: 16, color: C.stone, marginBottom: 6, lineHeight: 1.6 }}>
        {LEGAL_ENTRIES.length} free legal guides for New York. Plain language, verified, with free legal aid phone numbers.
      </p>
      <p style={{ fontSize: 13, color: C.dust, marginBottom: 18, lineHeight: 1.6 }}>
        Search any topic below, or pick a category. Every guide cites the law and lists free legal aid organizations.
      </p>

      {/* Search bar — searches across all entries by title, summary, and tags */}
      <div style={{ marginBottom: 22 }}>
        <input
          type="search"
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          placeholder="Search guides — try 'eviction', 'medicaid', 'speeding ticket'..."
          style={{
            width: "100%",
            padding: "14px 18px",
            fontSize: 16,
            fontFamily: "inherit",
            color: C.bark,
            background: C.white,
            border: "2px solid " + C.border,
            borderRadius: 12,
            outline: "none",
            boxSizing: "border-box",
            transition: "border-color 0.15s",
          }}
          onFocus={(e) => (e.currentTarget.style.borderColor = C.forest)}
          onBlur={(e) => (e.currentTarget.style.borderColor = C.border)}
        />
      </div>

      {/* Search results — shown in place of the category grid when query is active */}
      {trimmedQuery.length >= 2 ? (
        <div style={{ marginBottom: 22 }}>
          <div style={{ fontSize: 13, color: C.dust, marginBottom: 10 }}>
            {searchResults.length === 0
              ? "No matching guides. Try a different word."
              : searchResults.length + " match" + (searchResults.length === 1 ? "" : "es") + (searchResults.length === 40 ? " (showing first 40)" : "")}
          </div>
          <div style={{ display: "grid", gap: 10 }}>
            {searchResults.map((entry) => (
              <button
                key={entry.id}
                onClick={() => onOpenEntry && onOpenEntry(entry.id)}
                style={{
                  textAlign: isRTL ? "right" : "left",
                  background: C.white,
                  border: "1px solid " + C.border,
                  borderRadius: 10,
                  padding: "12px 16px",
                  cursor: "pointer",
                  fontFamily: "inherit",
                  width: "100%",
                }}
              >
                <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 4 }}>
                  <span style={{ fontSize: 10, fontWeight: 700, color: C.forest, background: C.sage, padding: "2px 7px", borderRadius: 5, textTransform: "uppercase", letterSpacing: 0.5 }}>{entry.tier}</span>
                  <span style={{ fontSize: 11, color: C.dust }}>{(CATEGORY_META[entry.category] || {}).label || entry.category}</span>
                </div>
                <div style={{ fontSize: 15, fontWeight: 600, color: C.bark, lineHeight: 1.3 }}>
                  {pickText(entry.title, legalLang)}
                </div>
              </button>
            ))}
          </div>
        </div>
      ) : null}

      <LanguagePicker legalLang={legalLang} setLegalLang={setLegalLang} />

      {/* Category tile grid */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(260px, 1fr))", gap: 14, marginTop: 8 }}>
        {categories.map((cat) => {
          const meta = CATEGORY_META[cat] || { icon: "📄", label: cat, desc: "" };
          const count = (LEGAL_ENTRIES_BY_CATEGORY[cat] || []).length;
          return (
            <button
              key={cat}
              onClick={() => onOpenCategory(cat)}
              style={{
                textAlign: isRTL ? "right" : "left",
                background: C.white,
                border: "1px solid " + C.border,
                borderRadius: 16,
                padding: "18px 20px",
                cursor: "pointer",
                fontFamily: "inherit",
                boxShadow: "0 1px 2px rgba(0,0,0,0.03)",
                transition: "all 0.15s",
                display: "flex",
                flexDirection: "column",
                gap: 8,
                minHeight: 140,
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.borderColor = C.forest;
                e.currentTarget.style.boxShadow = "0 4px 14px rgba(46,125,50,0.12)";
                e.currentTarget.style.transform = "translateY(-1px)";
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.borderColor = C.border;
                e.currentTarget.style.boxShadow = "0 1px 2px rgba(0,0,0,0.03)";
                e.currentTarget.style.transform = "translateY(0)";
              }}
            >
              <div style={{ fontSize: 36, lineHeight: 1 }}>{meta.icon}</div>
              <div style={{ fontSize: 18, fontWeight: 700, color: C.bark, fontFamily: SERIF }}>{meta.label}</div>
              <div style={{ fontSize: 13, color: C.stone, lineHeight: 1.5, flex: 1 }}>{meta.desc}</div>
              <div style={{ fontSize: 12, fontWeight: 600, color: C.forest, marginTop: 4 }}>
                {count} guide{count === 1 ? "" : "s"} →
              </div>
            </button>
          );
        })}
      </div>

      <div style={{ marginTop: 28, padding: "14px 18px", background: C.amberLight, borderRadius: 12, border: "1px solid #f0dab0", fontSize: 13, color: C.stone, lineHeight: 1.6 }}>
        ⚠️ <strong>Not legal advice.</strong> These guides explain your general rights under New York and federal law. Laws change. For your specific situation, use the free legal aid resources listed in each guide.
      </div>
    </main>
  );
}

// ═══════════════════════════════════════════════════════════════════════════
// CATEGORY BROWSE — entries filtered to one category
// ═══════════════════════════════════════════════════════════════════════════
export function LegalLibraryBrowse({ legalLang, setLegalLang, categoryFilter, onOpenEntry, onBack, jurisdictions = [] }) {
  const isRTL = RTL_LEGAL_LANGS.has(legalLang);
  const meta = CATEGORY_META[categoryFilter] || { icon: "📄", label: categoryFilter || "Guides", desc: "" };
  const allEntries = LEGAL_ENTRIES_BY_CATEGORY[categoryFilter] || [];

  // Jurisdiction filtering: town/village entries filter to user's location.
  // Federal, state, and county entries always show.
  const [showAll, setShowAll] = React.useState(false);
  const hasGeo = jurisdictions.length > 0;

  // Build jurisdiction slugs from geo matches: "Sweden" + "town" → "sweden-town"
  const geoSlugs = jurisdictions.map(j =>
    j.name.toLowerCase().replace(/\s+/g, '-') + '-' + j.tier
  );

  const filteredEntries = (!hasGeo || showAll) ? allEntries : allEntries.filter(entry => {
    // Always show federal, state, county entries
    if (entry.tier === 'federal' || entry.tier === 'state' || entry.tier === 'county') return true;
    // Town/village/city entries: check if jurisdiction matches any geo slug
    return geoSlugs.some(slug => entry.jurisdiction && entry.jurisdiction.endsWith(slug));
  });

  const entries = filteredEntries;
  const hiddenCount = allEntries.length - filteredEntries.length;

  // Library organization (added 2026-04-26):
  //   1. Walkthroughs (id ends with "-walkthrough-ny") pin to the top with
  //      an amber accent — they're the "do this with me" content vs the
  //      "here's how it works" reference content. Top placement reflects
  //      user value.
  //   2. Town-specific entries (jurisdiction matches us-ny-monroe-*-(town|
  //      village|city)) collapse into a "Local rules by town" section so
  //      they don't drown the state/federal guides.
  //   3. Everything else groups by tier: federal → state → county → other.
  const isWalkthrough = (e) => /-walkthrough-ny$/.test(e.id);
  const isTownSpecific = (e) => e.jurisdiction && /^us-ny-monroe-[^-]+-(town|village|city)$/.test(e.jurisdiction);
  const tierWeight = (e) => ({ federal: 0, state: 1, county: 2, town: 3, village: 3, city: 3, local: 3 }[e.tier] ?? 4);

  // In-category search — narrows the visible entries by title, summary, tags.
  const [query, setQuery] = React.useState("");
  const trimmedQuery = query.trim().toLowerCase();
  const searchedEntries = trimmedQuery.length < 2 ? entries : entries.filter((e) => {
    const title = (pickText(e.title, legalLang) || "").toLowerCase();
    const summary = (pickText(e.summary, legalLang) || "").toLowerCase();
    const tags = (e.tags || []).join(" ").toLowerCase();
    return title.includes(trimmedQuery) || summary.includes(trimmedQuery) || tags.includes(trimmedQuery);
  });

  const walkthroughEntries = searchedEntries.filter(isWalkthrough);
  const nonWalkthroughs = searchedEntries.filter((e) => !isWalkthrough(e));
  const mainEntries = nonWalkthroughs.filter((e) => !isTownSpecific(e)).sort((a, b) => tierWeight(a) - tierWeight(b));
  const townEntries = nonWalkthroughs.filter(isTownSpecific);
  const [showTownEntries, setShowTownEntries] = React.useState(false);

  return (
    <main dir={isRTL ? "rtl" : "ltr"} style={{ padding: "0 20px 40px", maxWidth: 920, margin: "0 auto" }}>
      <button onClick={onBack} style={{ background: "none", border: "none", cursor: "pointer", fontSize: 14, color: C.stone, padding: "16px 0", fontFamily: "inherit" }}>← All topics</button>

      <div style={{ display: "flex", alignItems: "center", gap: 14, marginBottom: 8 }}>
        <div style={{ fontSize: 40, lineHeight: 1 }}>{meta.icon}</div>
        <h1 style={{ fontFamily: SERIF, fontSize: 32, fontWeight: 400, margin: 0, color: C.bark, lineHeight: 1.2 }}>{meta.label}</h1>
      </div>
      <p style={{ fontSize: 14, color: C.stone, marginBottom: 6, lineHeight: 1.6 }}>{meta.desc}</p>
      <p style={{ fontSize: 12, color: C.dust, marginBottom: hasGeo && !showAll && hiddenCount > 0 ? 8 : 22 }}>
        {entries.length} guide{entries.length === 1 ? "" : "s"}
        {hasGeo && !showAll ? " for " + jurisdictions.map(j => j.displayName || j.name).join(" + ") : ""}
      </p>
      {hasGeo && hiddenCount > 0 && (
        <button
          onClick={() => setShowAll(!showAll)}
          style={{
            background: "none", border: "none", cursor: "pointer",
            fontSize: 12, color: C.forest, padding: "0 0 14px", fontFamily: "inherit",
            textDecoration: "underline"
          }}
        >
          {showAll ? "Show my area only" : "Show all " + allEntries.length + " jurisdictions"}
        </button>
      )}

      <LanguagePicker legalLang={legalLang} setLegalLang={setLegalLang} />

      {/* Search bar — filter within this category */}
      <div style={{ marginBottom: 18 }}>
        <input
          type="search"
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          placeholder={"Search " + meta.label.toLowerCase() + " guides..."}
          style={{
            width: "100%",
            padding: "12px 16px",
            fontSize: 15,
            fontFamily: "inherit",
            color: C.bark,
            background: C.white,
            border: "2px solid " + C.border,
            borderRadius: 10,
            outline: "none",
            boxSizing: "border-box",
            transition: "border-color 0.15s",
          }}
          onFocus={(e) => (e.currentTarget.style.borderColor = C.forest)}
          onBlur={(e) => (e.currentTarget.style.borderColor = C.border)}
        />
        {trimmedQuery.length >= 2 && (
          <div style={{ fontSize: 12, color: C.dust, marginTop: 6 }}>
            {searchedEntries.length} match{searchedEntries.length === 1 ? "" : "es"} in {meta.label}
          </div>
        )}
      </div>

      {/* Walkthroughs — pinned at top with amber accent (form prep guides) */}
      {walkthroughEntries.length > 0 && (
        <div style={{ marginBottom: 24 }}>
          <h2 style={{ fontSize: 14, fontWeight: 700, color: "#a07626", marginBottom: 10, textTransform: "uppercase", letterSpacing: 0.8 }}>
            📝 Form prep guides
          </h2>
          <div style={{ display: "grid", gap: 12 }}>
            {walkthroughEntries.map((entry) => (
              <button
                key={entry.id}
                onClick={() => onOpenEntry(entry.id)}
                style={{
                  textAlign: isRTL ? "right" : "left",
                  background: C.amberLight,
                  border: "1px solid " + C.amber,
                  borderRadius: 12,
                  padding: "14px 18px",
                  cursor: "pointer",
                  fontFamily: "inherit",
                  boxShadow: "0 1px 2px rgba(0,0,0,0.02)",
                  width: "100%",
                }}
              >
                <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 6 }}>
                  <span style={{ fontSize: 10, fontWeight: 700, color: "#a07626", background: "#fff7e6", padding: "3px 8px", borderRadius: 6, textTransform: "uppercase", letterSpacing: 0.5 }}>walkthrough</span>
                </div>
                <div style={{ fontSize: 16, fontWeight: 600, color: C.bark, marginBottom: 4, lineHeight: 1.3 }}>
                  {pickText(entry.title, legalLang)}
                </div>
                <div style={{ fontSize: 13, color: C.stone, lineHeight: 1.55 }}>
                  {pickText(entry.summary, legalLang)}
                </div>
              </button>
            ))}
          </div>
        </div>
      )}

      {/* Main entry list — federal/state/county sorted by tier */}
      <div style={{ display: "grid", gap: 12 }}>
        {mainEntries.map((entry) => (
          <button
            key={entry.id}
            onClick={() => onOpenEntry(entry.id)}
            style={{
              textAlign: isRTL ? "right" : "left",
              background: C.white,
              border: "1px solid " + C.border,
              borderRadius: 12,
              padding: "14px 18px",
              cursor: "pointer",
              fontFamily: "inherit",
              boxShadow: "0 1px 2px rgba(0,0,0,0.02)",
              width: "100%",
            }}
          >
            <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 6 }}>
              <span style={{ fontSize: 10, fontWeight: 700, color: C.forest, background: C.sage, padding: "3px 8px", borderRadius: 6, textTransform: "uppercase", letterSpacing: 0.5 }}>{entry.tier}</span>
              {entry.jurisdiction && (
                <span style={{ fontSize: 10, color: C.dust, textTransform: "uppercase", letterSpacing: 0.5 }}>{entry.jurisdiction}</span>
              )}
            </div>
            <div style={{ fontSize: 16, fontWeight: 600, color: C.bark, marginBottom: 4, lineHeight: 1.3 }}>
              {pickText(entry.title, legalLang)}
            </div>
            <div style={{ fontSize: 13, color: C.stone, lineHeight: 1.55 }}>
              {pickText(entry.summary, legalLang)}
            </div>
          </button>
        ))}
      </div>

      {/* Town-specific entries — collapsible section */}
      {townEntries.length > 0 && (
        <div style={{ marginTop: 24 }}>
          <button
            onClick={() => setShowTownEntries(!showTownEntries)}
            style={{
              background: C.cream, border: "1px solid " + C.border,
              borderRadius: 10, padding: "12px 16px", cursor: "pointer",
              fontFamily: "inherit", fontSize: 14, fontWeight: 600, color: C.stone,
              width: "100%", textAlign: isRTL ? "right" : "left",
              display: "flex", alignItems: "center", justifyContent: "space-between",
            }}
          >
            <span>🏘️ Local rules by town ({townEntries.length})</span>
            <span style={{ fontSize: 12, color: C.dust }}>{showTownEntries ? "▲ hide" : "▼ show"}</span>
          </button>
          {showTownEntries && (
            <div style={{ display: "grid", gap: 12, marginTop: 12 }}>
              {townEntries.map((entry) => (
                <button
                  key={entry.id}
                  onClick={() => onOpenEntry(entry.id)}
                  style={{
                    textAlign: isRTL ? "right" : "left",
                    background: C.white,
                    border: "1px solid " + C.border,
                    borderRadius: 12,
                    padding: "14px 18px",
                    cursor: "pointer",
                    fontFamily: "inherit",
                    boxShadow: "0 1px 2px rgba(0,0,0,0.02)",
                    width: "100%",
                  }}
                >
                  <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 6 }}>
                    <span style={{ fontSize: 10, fontWeight: 700, color: C.forest, background: C.sage, padding: "3px 8px", borderRadius: 6, textTransform: "uppercase", letterSpacing: 0.5 }}>{entry.tier}</span>
                    {entry.jurisdiction && (
                      <span style={{ fontSize: 10, color: C.dust, textTransform: "uppercase", letterSpacing: 0.5 }}>{entry.jurisdiction}</span>
                    )}
                  </div>
                  <div style={{ fontSize: 16, fontWeight: 600, color: C.bark, marginBottom: 4, lineHeight: 1.3 }}>
                    {pickText(entry.title, legalLang)}
                  </div>
                  <div style={{ fontSize: 13, color: C.stone, lineHeight: 1.55 }}>
                    {pickText(entry.summary, legalLang)}
                  </div>
                </button>
              ))}
            </div>
          )}
        </div>
      )}

      <div style={{ marginTop: 28, padding: "14px 18px", background: C.amberLight, borderRadius: 12, border: "1px solid #f0dab0", fontSize: 13, color: C.stone, lineHeight: 1.6 }}>
        ⚠️ <strong>Not legal advice.</strong> These guides explain your general rights under New York and federal law. Laws change. For your specific situation, use the free legal aid resources listed in each guide.
      </div>
    </main>
  );
}

// ═══════════════════════════════════════════════════════════════════════════
// SHARE BAR — share individual entry pages to socials, text, email, or copy link
// ═══════════════════════════════════════════════════════════════════════════
function ShareBar({ entryId, title }) {
  const [copied, setCopied] = React.useState(false);
  const url = "https://helpfinder.help/know-your-rights/" + entryId;
  const text = title + " — free legal guide from HelpFinder, the only .help you need";
  const encodedUrl = encodeURIComponent(url);
  const encodedText = encodeURIComponent(text);

  const copyLink = () => {
    navigator.clipboard.writeText(url).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }).catch(() => {
      const ta = document.createElement("textarea");
      ta.value = url;
      document.body.appendChild(ta);
      ta.select();
      document.execCommand("copy");
      document.body.removeChild(ta);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const nativeShare = () => {
    if (navigator.share) {
      navigator.share({ title: title, text: text, url: url }).catch(() => {});
    }
  };

  const btnBase = {
    display: "inline-flex", alignItems: "center", justifyContent: "center",
    gap: 5, padding: "7px 12px", borderRadius: 8, border: "1px solid " + C.border,
    background: C.white, cursor: "pointer", fontFamily: "inherit",
    fontSize: 12, fontWeight: 600, lineHeight: 1, whiteSpace: "nowrap",
  };

  return (
    <div style={{ display: "flex", flexWrap: "wrap", gap: 6, alignItems: "center", margin: "16px 0" }}>
      <span style={{ fontSize: 12, color: C.dust, fontWeight: 600, marginRight: 4 }}>Share:</span>
      <button onClick={copyLink} style={{ ...btnBase, color: copied ? C.forest : C.bark, background: copied ? C.sage : C.white }}>
        {copied ? "Copied" : "Copy link"}
      </button>
      <a href={"https://www.facebook.com/sharer/sharer.php?u=" + encodedUrl} target="_blank" rel="noopener noreferrer"
        style={{ ...btnBase, color: "#1877F2", textDecoration: "none" }}>
        Facebook
      </a>
      <a href={"https://twitter.com/intent/tweet?url=" + encodedUrl + "&text=" + encodedText} target="_blank" rel="noopener noreferrer"
        style={{ ...btnBase, color: "#000", textDecoration: "none" }}>
        X
      </a>
      <a href={"mailto:?subject=" + encodeURIComponent(title) + "&body=" + encodedText + "%0A%0A" + encodedUrl}
        style={{ ...btnBase, color: C.bark, textDecoration: "none" }}>
        Email
      </a>
      <a href={"sms:?body=" + encodedText + " " + encodedUrl}
        style={{ ...btnBase, color: C.forest, textDecoration: "none" }}>
        Text
      </a>
      {typeof navigator !== "undefined" && navigator.share && (
        <button onClick={nativeShare} style={{ ...btnBase, color: C.forest }}>
          More
        </button>
      )}
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════════════════
// ENTRY DETAIL
// ═══════════════════════════════════════════════════════════════════════════
// Sticky right-rail TOC for entry pages on desktop. Hidden on viewport
// below 1100px (article falls back to single-column on tablet/mobile).
function EntryTocSidebar({ sections, isRTL }) {
  return (
    <aside style={{
      width: 240, flexShrink: 0,
      position: "sticky", top: 16, alignSelf: "flex-start",
      maxHeight: "calc(100vh - 32px)", overflowY: "auto",
      paddingTop: 70,
      [isRTL ? "marginRight" : "marginLeft"]: 28,
    }}>
      <div style={{ fontSize: 11, fontWeight: 700, color: C.dust, marginBottom: 10, textTransform: "uppercase", letterSpacing: 0.6 }}>On this page</div>
      <nav style={{ display: "flex", flexDirection: "column", gap: 2, marginBottom: 24, borderLeft: "2px solid " + C.border, paddingLeft: 0 }}>
        {sections.map(s => (
          <a key={s.id} href={"#" + s.id} style={{
            color: C.stone, fontSize: 13, textDecoration: "none",
            padding: "6px 12px", marginLeft: -2,
            borderLeft: "2px solid transparent",
            lineHeight: 1.4,
          }}>{s.label}</a>
        ))}
      </nav>
      <a href="/support" style={{
        display: "block", padding: "14px 16px",
        background: C.amberLight, border: "1px solid " + C.amber,
        borderRadius: 12, color: "#a07626", fontSize: 13, fontWeight: 600,
        textDecoration: "none", lineHeight: 1.5,
      }}>
        <div style={{ fontSize: 14, marginBottom: 4 }}>❤️ Keep this free</div>
        <div style={{ fontWeight: 400, fontSize: 12, color: C.stone }}>HelpFinder is free for everyone. If you can chip in, it covers hosting and verification.</div>
      </a>
    </aside>
  );
}

function useIsDesktop(minWidth = 1100) {
  const [is, setIs] = React.useState(() =>
    typeof window !== "undefined" && window.matchMedia("(min-width: " + minWidth + "px)").matches
  );
  React.useEffect(() => {
    if (typeof window === "undefined") return;
    const mq = window.matchMedia("(min-width: " + minWidth + "px)");
    const h = (e) => setIs(e.matches);
    if (mq.addEventListener) mq.addEventListener("change", h);
    else mq.addListener(h);
    return () => {
      if (mq.removeEventListener) mq.removeEventListener("change", h);
      else mq.removeListener(h);
    };
  }, [minWidth]);
  return is;
}

export function LegalLibraryEntry({ entryId, legalLang, setLegalLang, onBack, onOpenEntry }) {
  const entry = entryId ? LEGAL_ENTRIES_BY_ID[entryId] : null;
  const isDesktop = useIsDesktop(1100);
  if (!entry) {
    return (
      <main style={{ padding: "40px 20px", maxWidth: 900, margin: "0 auto" }}>
        <button onClick={onBack} style={{ background: "none", border: "none", cursor: "pointer", fontSize: 14, color: C.stone, padding: "16px 0", fontFamily: "inherit" }}>← Back</button>
        <p style={{ color: C.stone }}>Guide not found.</p>
      </main>
    );
  }

  const isRTL = RTL_LEGAL_LANGS.has(legalLang);
  const whoQualArr = pickArr(entry.whoQualifies, legalLang);
  const rightsArr = pickArr(entry.yourRights, legalLang);
  const optionsArr = pickArr(entry.legalOptions, legalLang);
  const relIds = (entry.relatedIds || []).filter((rid) => LEGAL_ENTRIES_BY_ID[rid]);
  const catMeta = CATEGORY_META[entry.category] || { label: entry.category };

  // Build the TOC list from the sections that actually render for this entry.
  const tocSections = [];
  if (whoQualArr.length > 0) tocSections.push({ id: "who-qualifies", label: "Who qualifies" });
  if (entry.whatItMeans) tocSections.push({ id: "what-it-means", label: "What it means" });
  if (rightsArr.length > 0) tocSections.push({ id: "your-rights", label: "Your rights" });
  if (optionsArr.length > 0) tocSections.push({ id: "legal-options", label: "Legal options" });
  if (entry.example) tocSections.push({ id: "example", label: "Example" });
  if (entry.counsel && entry.counsel.length > 0) tocSections.push({ id: "get-free-help", label: "Get free legal help" });
  if (relIds.length > 0) tocSections.push({ id: "related-guides", label: "Related guides" });
  if (entry.sources && entry.sources.length > 0) tocSections.push({ id: "sources", label: "Sources & citations" });

  // Wrapper layout — desktop adds a sticky right-rail TOC; mobile/tablet keeps single-column.
  const outerStyle = isDesktop
    ? { padding: "0 20px 40px", maxWidth: 1180, margin: "0 auto", display: "flex", alignItems: "flex-start", gap: 0 }
    : { padding: "0 20px 40px", maxWidth: 900, margin: "0 auto" };
  const articleStyle = isDesktop
    ? { flex: 1, minWidth: 0, maxWidth: 820 }
    : {};

  return (
    <main dir={isRTL ? "rtl" : "ltr"} style={outerStyle}>
      <div style={articleStyle}>
      <button onClick={onBack} style={{ background: "none", border: "none", cursor: "pointer", fontSize: 14, color: C.stone, padding: "16px 0", fontFamily: "inherit" }}>← Back to {catMeta.label}</button>

      <LanguagePicker legalLang={legalLang} setLegalLang={setLegalLang} compact availableLangs={availableLangsForEntry(entry)} />

      <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 10, flexWrap: "wrap" }}>
        <span style={{ fontSize: 10, fontWeight: 700, color: C.forest, background: C.sage, padding: "3px 8px", borderRadius: 6, textTransform: "uppercase", letterSpacing: 0.5 }}>{entry.tier}</span>
        <span style={{ fontSize: 11, color: C.dust, textTransform: "uppercase", letterSpacing: 0.5 }}>
          {catMeta.label}{entry.jurisdiction ? " · " + entry.jurisdiction.toUpperCase() : ""}
        </span>
      </div>

      <h1 style={{ fontFamily: SERIF, fontSize: 32, fontWeight: 400, marginBottom: 14, color: C.bark, lineHeight: 1.25 }}>
        {pickText(entry.title, legalLang)}
      </h1>

      <p style={{ fontSize: 17, color: C.stone, lineHeight: 1.6, marginBottom: 20, fontWeight: 500 }}>
        {pickText(entry.summary, legalLang)}
      </p>

      <AuthorityBadge authorityType={entry.authorityType} />

      <VerifiedBadge lastVerified={entry.lastVerified || entry.lastAudited} />

      <ShareBar entryId={entry.id} title={pickText(entry.title, "en")} />

      {entry.reviewedBy && (
        <div style={{
          marginBottom: 24,
          padding: "14px 18px",
          background: C.sage,
          borderRadius: 12,
          border: "1px solid #c8e6c9",
          fontSize: 13,
          lineHeight: 1.55,
        }}>
          <div style={{ color: C.forest, fontWeight: 600, marginBottom: 6, display: "flex", alignItems: "center", gap: 6 }}>
            <span style={{ fontSize: 14 }}>✓</span>
            <span>Reviewed by {entry.reviewedBy}</span>
          </div>
          <div style={{ color: C.stone, fontStyle: "italic" }}>
            This guide is general legal information, not legal advice for your specific situation.
          </div>
        </div>
      )}

      {whoQualArr.length > 0 && (
        <section id="who-qualifies" style={{ marginBottom: 26, scrollMarginTop: 20 }}>
          <h2 style={{ fontFamily: SERIF, fontSize: 22, fontWeight: 400, marginBottom: 12, color: C.bark }}>Who qualifies</h2>
          <ul style={{ margin: 0, paddingLeft: isRTL ? 0 : 22, paddingRight: isRTL ? 22 : 0, fontSize: 15, color: C.bark, lineHeight: 1.7 }}>
            {whoQualArr.map((item, i) => <li key={i} style={{ marginBottom: 8 }}>{item}</li>)}
          </ul>
        </section>
      )}

      {entry.whatItMeans && (
        <section id="what-it-means" style={{ marginBottom: 26, scrollMarginTop: 20 }}>
          <h2 style={{ fontFamily: SERIF, fontSize: 22, fontWeight: 400, marginBottom: 12, color: C.bark }}>What it means</h2>
          <p style={{ fontSize: 15, color: C.bark, lineHeight: 1.8, margin: 0, whiteSpace: "pre-wrap" }}>
            <GlossaryText text={pickText(entry.whatItMeans, legalLang)} maxHighlights={3} />
          </p>
        </section>
      )}

      {rightsArr.length > 0 && (
        <section id="your-rights" style={{ marginBottom: 26, padding: "18px 22px", background: C.sage, borderRadius: 14, border: "1px solid #c8e6c9", scrollMarginTop: 20 }}>
          <h2 style={{ fontFamily: SERIF, fontSize: 22, fontWeight: 400, marginBottom: 12, color: C.forest }}>Your rights</h2>
          <ul style={{ margin: 0, paddingLeft: isRTL ? 0 : 22, paddingRight: isRTL ? 22 : 0, fontSize: 15, color: C.bark, lineHeight: 1.7 }}>
            {rightsArr.map((item, i) => <li key={i} style={{ marginBottom: 8 }}><GlossaryText text={item} maxHighlights={2} /></li>)}
          </ul>
        </section>
      )}

      {optionsArr.length > 0 && (
        <section id="legal-options" style={{ marginBottom: 26, scrollMarginTop: 20 }}>
          <h2 style={{ fontFamily: SERIF, fontSize: 22, fontWeight: 400, marginBottom: 12, color: C.bark }}>Legal options</h2>
          <ul style={{ margin: 0, paddingLeft: isRTL ? 0 : 22, paddingRight: isRTL ? 22 : 0, fontSize: 15, color: C.bark, lineHeight: 1.7 }}>
            {optionsArr.map((item, i) => <li key={i} style={{ marginBottom: 10 }}><GlossaryText text={item} maxHighlights={2} /></li>)}
          </ul>
        </section>
      )}

      {entry.example && (
        <section id="example" style={{ marginBottom: 26, padding: "18px 22px", background: C.amberLight, borderRadius: 14, border: "1px solid #f0dab0", scrollMarginTop: 20 }}>
          <h2 style={{ fontFamily: SERIF, fontSize: 20, fontWeight: 400, marginBottom: 10, color: C.bark }}>Example</h2>
          <p style={{ fontSize: 14, color: C.stone, lineHeight: 1.7, margin: 0, fontStyle: "italic" }}>
            <GlossaryText text={pickText(entry.example, legalLang)} maxHighlights={2} />
          </p>
          <p style={{ fontSize: 12, color: C.stone, opacity: 0.65, lineHeight: 1.5, margin: "10px 0 0 0", fontStyle: "italic" }}>
            Examples on this page are illustrations. The names, numbers, and outcomes are made up to show how the law works in a typical situation. They are not a prediction of what will happen in a real case.
          </p>
        </section>
      )}

      {entry.counsel && entry.counsel.length > 0 && (
        <section id="get-free-help" style={{ marginBottom: 26, scrollMarginTop: 20 }}>
          <h2 style={{ fontFamily: SERIF, fontSize: 22, fontWeight: 400, marginBottom: 12, color: C.bark }}>Get free legal help</h2>
          <div style={{ display: "grid", gap: 12 }}>
            {entry.counsel.map((c, i) => (
              <div key={i} style={{ padding: "14px 18px", background: C.white, borderRadius: 12, border: "1px solid " + C.border }}>
                <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 6 }}>
                  <span style={{ fontSize: 9, fontWeight: 700, color: C.forest, background: C.sage, padding: "2px 7px", borderRadius: 5, textTransform: "uppercase", letterSpacing: 0.5 }}>{c.type || "free"}</span>
                  {c.verified && <span style={{ fontSize: 10, color: C.forest }}>✓ verified</span>}
                </div>
                <div style={{ fontSize: 15, fontWeight: 600, color: C.bark, marginBottom: 4 }}>{c.name}</div>
                {c.focus && <div style={{ fontSize: 13, color: C.stone, marginBottom: 4 }}>{c.focus}</div>}
                {c.qualifier && <div style={{ fontSize: 12, color: C.dust, marginBottom: 8, fontStyle: "italic" }}>{c.qualifier}</div>}
                <div style={{ display: "flex", gap: 12, flexWrap: "wrap", alignItems: "center" }}>
                  {c.phone && (
                    <a href={"tel:" + c.phone.replace(/[^0-9+]/g, "")} style={{ background: C.forest, color: C.white, padding: "8px 16px", borderRadius: 8, fontSize: 14, fontWeight: 600, textDecoration: "none" }}>
                      📞 {c.phone}
                    </a>
                  )}
                  {c.url && (
                    <a href={c.url} target="_blank" rel="noopener noreferrer" style={{ color: C.forest, fontSize: 13, textDecoration: "underline" }}>
                      website ↗
                    </a>
                  )}
                </div>
              </div>
            ))}
          </div>
        </section>
      )}

      {relIds.length > 0 && (
        <section id="related-guides" style={{ marginBottom: 26, scrollMarginTop: 20 }}>
          <h2 style={{ fontFamily: SERIF, fontSize: 20, fontWeight: 400, marginBottom: 12, color: C.bark }}>Related guides</h2>
          <div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>
            {relIds.map((rid) => (
              <button
                key={rid}
                onClick={() => onOpenEntry(rid)}
                style={{ background: C.white, border: "1px solid " + C.border, borderRadius: 8, padding: "8px 14px", cursor: "pointer", fontFamily: "inherit", fontSize: 13, color: C.forest }}
              >
                {pickText(LEGAL_ENTRIES_BY_ID[rid].title, legalLang)}
              </button>
            ))}
          </div>
        </section>
      )}

      {entry.sources && entry.sources.length > 0 && (
        <section id="sources" style={{ marginBottom: 20, paddingTop: 20, borderTop: "1px solid " + C.border, scrollMarginTop: 20 }}>
          <div style={{ fontSize: 12, fontWeight: 600, color: C.stone, marginBottom: 10, textTransform: "uppercase", letterSpacing: 0.5 }}>Sources & citations</div>
          <ul style={{ margin: 0, paddingLeft: isRTL ? 0 : 20, paddingRight: isRTL ? 20 : 0, fontSize: 13, color: C.bark, lineHeight: 1.6 }}>
            {entry.sources.map((s, i) => {
              const p = parseSource(s);
              return (
                <li key={i} style={{ marginBottom: 6 }}>
                  <a href={p.url} target="_blank" rel="noopener noreferrer" style={{ color: C.forest, fontWeight: 500, textDecoration: "none" }}>
                    {p.label}
                  </a>
                  {p.host && <span style={{ fontSize: 11, color: C.dust, marginLeft: 6 }}>↗ {p.host}</span>}
                </li>
              );
            })}
          </ul>
        </section>
      )}

      {GLOSSARY_TERMS_BY_CATEGORY[entry.category] && GLOSSARY_TERMS_BY_CATEGORY[entry.category].length > 0 && (
        <a
          href={"/glossary/category/" + entry.category}
          style={{
            display: "flex", alignItems: "center", gap: 10,
            marginTop: 20, padding: "12px 16px",
            background: "#ede7f6", border: "1px solid #5e35b1",
            borderRadius: 10, color: "#4527a0",
            fontSize: 14, fontWeight: 600, textDecoration: "none",
          }}
        >
          <span style={{ fontSize: 20 }}>📖</span>
          <span style={{ flex: 1 }}>Common phrases in this topic — {GLOSSARY_TERMS_BY_CATEGORY[entry.category].length} words explained</span>
          <span>→</span>
        </a>
      )}
      <div style={{ fontSize: 11, color: C.dust, marginTop: 14, paddingTop: 12, borderTop: "1px solid " + C.border }}>
        Last audited: {entry.lastAudited || "unknown"} · Entry ID: {entry.id}
      </div>

      <ShareBar entryId={entry.id} title={pickText(entry.title, "en")} />

      <div style={{ marginTop: 20, padding: "14px 18px", background: C.amberLight, borderRadius: 12, border: "1px solid #f0dab0", fontSize: 12, color: C.stone, lineHeight: 1.6 }}>
        ⚠️ <strong>Not legal advice.</strong> This guide explains your general rights. Laws change. For your specific situation, contact one of the free legal aid organizations listed above.
      </div>

      {/* Always-visible support nudge — mobile + desktop both. Subtle, not aggressive. */}
      <a href="/support" style={{
        display: "flex", alignItems: "center", gap: 12,
        marginTop: 18, padding: "14px 18px",
        background: C.white, border: "1px solid " + C.border,
        borderRadius: 12, textDecoration: "none",
      }}>
        <span style={{ fontSize: 22 }}>❤️</span>
        <div style={{ flex: 1 }}>
          <div style={{ fontSize: 14, fontWeight: 700, color: C.bark }}>Keep HelpFinder free</div>
          <div style={{ fontSize: 12, color: C.stone, lineHeight: 1.5, marginTop: 2 }}>
            No paywall, no ads. If this guide helped, a small contribution keeps it up to date for the next person.
          </div>
        </div>
        <span style={{ fontSize: 14, fontWeight: 700, color: C.forest }}>Support →</span>
      </a>
      </div>
      {isDesktop && tocSections.length > 0 && (
        <EntryTocSidebar sections={tocSections} isRTL={isRTL} />
      )}
    </main>
  );
}
