import React from "react";
// AUTO-GENERATED by step8a_category_tiles.cjs
// Legal Library: category overview + filtered browse + entry detail.
//
// Exported components:
//   LegalLibraryCategories — top-level category tile overview (7 tiles)
//   LegalLibraryBrowse     — entries filtered to one category
//   LegalLibraryEntry      — detail view for a single entry

import { LEGAL_ENTRIES, LEGAL_ENTRIES_BY_ID, LEGAL_ENTRIES_BY_CATEGORY, LEGAL_CATEGORIES } from "../data/legal";
import { GLOSSARY_TERMS_BY_CATEGORY } from "../data/legal/glossary-index";
import { LEGAL_LANGS, RTL_LEGAL_LANGS } from "../data/legal/langs";

const C = {
  forest: "#2e7d32", leaf: "#43a047", sage: "#e8f5e9",
  warmBg: "#fafaf7", cream: "#f5f0e8", bark: "#1a1a1a",
  stone: "#555", dust: "#767676", amber: "#d4a056",
  amberLight: "#fdf6ec", white: "#fff", border: "#e8e4dc",
};

const SERIF = "'DM Serif Display', Georgia, serif";

// Category metadata — icons, labels, and short descriptions for the tiles
export const CATEGORY_META = {
  benefits: {
    icon: "💰",
    label: "Money & Benefits",
    desc: "SNAP, Medicaid, Medicare, cash help, disability, fair hearings, appeals.",
  },
  consumer: {
    icon: "🛒",
    label: "Debt & Money Problems",
    desc: "Debt collection, scams, contracts, refunds, unfair charges.",
  },
  housing: {
    icon: "🏠",
    label: "Housing & Rent",
    desc: "Landlord disputes, eviction, security deposits, housing discrimination.",
  },
  family: {
    icon: "👨‍👩‍👧",
    label: "Family Decisions",
    desc: "Child care, custody, planning ahead with Power of Attorney or Health Care Proxy, guardianship alternatives.",
  },
  employment: {
    icon: "💼",
    label: "Work & Pay",
    desc: "Wage theft, unpaid wages, overtime, wrongful firing, workplace rights.",
  },
  vehicle: {
    icon: "🚗",
    label: "Driving & Tickets",
    desc: "Driver's license, suspensions, registration, tickets, DWI.",
  },
  criminal: {
    icon: "⚖️",
    label: "Arrests & Records",
    desc: "Rights when arrested, drug charges, Good Samaritan Law, sealing or expunging a record.",
  },
  trades: {
    icon: "🔨",
    label: "Home Projects & Permits",
    desc: "Building permits, contractor rules, and local ordinances for roofing, plumbing, electrical, and HVAC work.",
  },
};

function pickText(field, lang) {
  if (!field) return "";
  return field[lang] || field.en || "";
}
function pickArr(field, lang) {
  if (!field) return [];
  return field[lang] || field.en || [];
}

function LanguagePicker({ legalLang, setLegalLang, compact }) {
  return (
    <div style={{
      marginBottom: compact ? 20 : 28,
      padding: compact ? "10px 14px" : "12px 16px",
      background: C.cream, borderRadius: compact ? 10 : 12,
      border: "1px solid " + C.border,
      display: "inline-flex", alignItems: "center", gap: 8, flexWrap: "wrap",
    }}>
      <label style={{ fontSize: compact ? 12 : 13, color: C.stone, fontWeight: 500 }}>🌐 Read in:</label>
      <select
        value={legalLang}
        onChange={(e) => setLegalLang(e.target.value)}
        style={{
          padding: compact ? "4px 10px" : "6px 12px",
          fontSize: compact ? 13 : 14,
          borderRadius: compact ? 6 : 8,
          border: "1px solid " + C.border,
          background: C.white, fontFamily: "inherit", color: C.bark, cursor: "pointer",
        }}
      >
        {LEGAL_LANGS.map((l) => (
          <option key={l.code} value={l.code}>{l.label}</option>
        ))}
      </select>
    </div>
  );
}

// ═══════════════════════════════════════════════════════════════════════════
// CATEGORY OVERVIEW — 7 big tiles
// ═══════════════════════════════════════════════════════════════════════════
export function LegalLibraryCategories({ legalLang, setLegalLang, onOpenCategory, onBack }) {
  const isRTL = RTL_LEGAL_LANGS.has(legalLang);
  // Only show categories that actually have entries
  const categories = LEGAL_CATEGORIES.filter((c) => (LEGAL_ENTRIES_BY_CATEGORY[c] || []).length > 0);

  return (
    <main dir={isRTL ? "rtl" : "ltr"} style={{ padding: "0 20px 40px", maxWidth: 920, margin: "0 auto" }}>
      <button onClick={onBack} style={{ background: "none", border: "none", cursor: "pointer", fontSize: 14, color: C.stone, padding: "16px 0", fontFamily: "inherit" }}>← Back</button>

      <h1 style={{ fontFamily: SERIF, fontSize: 36, fontWeight: 400, marginBottom: 6, color: C.bark, lineHeight: 1.2 }}>Know Your Rights</h1>
      <p style={{ fontSize: 16, color: C.stone, marginBottom: 6, lineHeight: 1.6 }}>
        {LEGAL_ENTRIES.length} free legal guides for New York. Plain language, verified, with free legal aid phone numbers.
      </p>
      <p style={{ fontSize: 13, color: C.dust, marginBottom: 22, lineHeight: 1.6 }}>
        Pick a topic below to see the guides. Every guide cites the law and lists free legal aid organizations.
      </p>

      <LanguagePicker legalLang={legalLang} setLegalLang={setLegalLang} />

      {/* Category tile grid */}
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(260px, 1fr))", gap: 14, marginTop: 8 }}>
        {categories.map((cat) => {
          const meta = CATEGORY_META[cat] || { icon: "📄", label: cat, desc: "" };
          const count = (LEGAL_ENTRIES_BY_CATEGORY[cat] || []).length;
          return (
            <button
              key={cat}
              onClick={() => onOpenCategory(cat)}
              style={{
                textAlign: isRTL ? "right" : "left",
                background: C.white,
                border: "1px solid " + C.border,
                borderRadius: 16,
                padding: "18px 20px",
                cursor: "pointer",
                fontFamily: "inherit",
                boxShadow: "0 1px 2px rgba(0,0,0,0.03)",
                transition: "all 0.15s",
                display: "flex",
                flexDirection: "column",
                gap: 8,
                minHeight: 140,
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.borderColor = C.forest;
                e.currentTarget.style.boxShadow = "0 4px 14px rgba(46,125,50,0.12)";
                e.currentTarget.style.transform = "translateY(-1px)";
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.borderColor = C.border;
                e.currentTarget.style.boxShadow = "0 1px 2px rgba(0,0,0,0.03)";
                e.currentTarget.style.transform = "translateY(0)";
              }}
            >
              <div style={{ fontSize: 36, lineHeight: 1 }}>{meta.icon}</div>
              <div style={{ fontSize: 18, fontWeight: 700, color: C.bark, fontFamily: SERIF }}>{meta.label}</div>
              <div style={{ fontSize: 13, color: C.stone, lineHeight: 1.5, flex: 1 }}>{meta.desc}</div>
              <div style={{ fontSize: 12, fontWeight: 600, color: C.forest, marginTop: 4 }}>
                {count} guide{count === 1 ? "" : "s"} →
              </div>
            </button>
          );
        })}
      </div>

      <div style={{ marginTop: 28, padding: "14px 18px", background: C.amberLight, borderRadius: 12, border: "1px solid #f0dab0", fontSize: 13, color: C.stone, lineHeight: 1.6 }}>
        ⚠️ <strong>Not legal advice.</strong> These guides explain your general rights under New York and federal law. Laws change. For your specific situation, use the free legal aid resources listed in each guide.
      </div>
    </main>
  );
}

// ═══════════════════════════════════════════════════════════════════════════
// CATEGORY BROWSE — entries filtered to one category
// ═══════════════════════════════════════════════════════════════════════════
export function LegalLibraryBrowse({ legalLang, setLegalLang, categoryFilter, onOpenEntry, onBack, jurisdictions = [] }) {
  const isRTL = RTL_LEGAL_LANGS.has(legalLang);
  const meta = CATEGORY_META[categoryFilter] || { icon: "📄", label: categoryFilter || "Guides", desc: "" };
  const allEntries = LEGAL_ENTRIES_BY_CATEGORY[categoryFilter] || [];

  // Jurisdiction filtering: town/village entries filter to user's location.
  // Federal, state, and county entries always show.
  const [showAll, setShowAll] = React.useState(false);
  const hasGeo = jurisdictions.length > 0;

  // Build jurisdiction slugs from geo matches: "Sweden" + "town" → "sweden-town"
  const geoSlugs = jurisdictions.map(j =>
    j.name.toLowerCase().replace(/\s+/g, '-') + '-' + j.tier
  );

  const filteredEntries = (!hasGeo || showAll) ? allEntries : allEntries.filter(entry => {
    // Always show federal, state, county entries
    if (entry.tier === 'federal' || entry.tier === 'state' || entry.tier === 'county') return true;
    // Town/village/city entries: check if jurisdiction matches any geo slug
    return geoSlugs.some(slug => entry.jurisdiction && entry.jurisdiction.endsWith(slug));
  });

  const entries = filteredEntries;
  const hiddenCount = allEntries.length - filteredEntries.length;

  return (
    <main dir={isRTL ? "rtl" : "ltr"} style={{ padding: "0 20px 40px", maxWidth: 920, margin: "0 auto" }}>
      <button onClick={onBack} style={{ background: "none", border: "none", cursor: "pointer", fontSize: 14, color: C.stone, padding: "16px 0", fontFamily: "inherit" }}>← All topics</button>

      <div style={{ display: "flex", alignItems: "center", gap: 14, marginBottom: 8 }}>
        <div style={{ fontSize: 40, lineHeight: 1 }}>{meta.icon}</div>
        <h1 style={{ fontFamily: SERIF, fontSize: 32, fontWeight: 400, margin: 0, color: C.bark, lineHeight: 1.2 }}>{meta.label}</h1>
      </div>
      <p style={{ fontSize: 14, color: C.stone, marginBottom: 6, lineHeight: 1.6 }}>{meta.desc}</p>
      <p style={{ fontSize: 12, color: C.dust, marginBottom: hasGeo && !showAll && hiddenCount > 0 ? 8 : 22 }}>
        {entries.length} guide{entries.length === 1 ? "" : "s"}
        {hasGeo && !showAll ? " for " + jurisdictions.map(j => j.displayName || j.name).join(" + ") : ""}
      </p>
      {hasGeo && hiddenCount > 0 && (
        <button
          onClick={() => setShowAll(!showAll)}
          style={{
            background: "none", border: "none", cursor: "pointer",
            fontSize: 12, color: C.forest, padding: "0 0 14px", fontFamily: "inherit",
            textDecoration: "underline"
          }}
        >
          {showAll ? "Show my area only" : "Show all " + allEntries.length + " jurisdictions"}
        </button>
      )}

      <LanguagePicker legalLang={legalLang} setLegalLang={setLegalLang} />

      {/* Entry list */}
      <div style={{ display: "grid", gap: 12 }}>
        {entries.map((entry) => (
          <button
            key={entry.id}
            onClick={() => onOpenEntry(entry.id)}
            style={{
              textAlign: isRTL ? "right" : "left",
              background: C.white,
              border: "1px solid " + C.border,
              borderRadius: 12,
              padding: "14px 18px",
              cursor: "pointer",
              fontFamily: "inherit",
              boxShadow: "0 1px 2px rgba(0,0,0,0.02)",
              width: "100%",
            }}
          >
            <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 6 }}>
              <span style={{ fontSize: 10, fontWeight: 700, color: C.forest, background: C.sage, padding: "3px 8px", borderRadius: 6, textTransform: "uppercase", letterSpacing: 0.5 }}>{entry.tier}</span>
              {entry.jurisdiction && (
                <span style={{ fontSize: 10, color: C.dust, textTransform: "uppercase", letterSpacing: 0.5 }}>{entry.jurisdiction}</span>
              )}
            </div>
            <div style={{ fontSize: 16, fontWeight: 600, color: C.bark, marginBottom: 4, lineHeight: 1.3 }}>
              {pickText(entry.title, legalLang)}
            </div>
            <div style={{ fontSize: 13, color: C.stone, lineHeight: 1.55 }}>
              {pickText(entry.summary, legalLang)}
            </div>
          </button>
        ))}
      </div>

      <div style={{ marginTop: 28, padding: "14px 18px", background: C.amberLight, borderRadius: 12, border: "1px solid #f0dab0", fontSize: 13, color: C.stone, lineHeight: 1.6 }}>
        ⚠️ <strong>Not legal advice.</strong> These guides explain your general rights under New York and federal law. Laws change. For your specific situation, use the free legal aid resources listed in each guide.
      </div>
    </main>
  );
}

// ═══════════════════════════════════════════════════════════════════════════
// ENTRY DETAIL — unchanged from step 2
// ═══════════════════════════════════════════════════════════════════════════
export function LegalLibraryEntry({ entryId, legalLang, setLegalLang, onBack, onOpenEntry }) {
  const entry = entryId ? LEGAL_ENTRIES_BY_ID[entryId] : null;
  if (!entry) {
    return (
      <main style={{ padding: "40px 20px", maxWidth: 900, margin: "0 auto" }}>
        <button onClick={onBack} style={{ background: "none", border: "none", cursor: "pointer", fontSize: 14, color: C.stone, padding: "16px 0", fontFamily: "inherit" }}>← Back</button>
        <p style={{ color: C.stone }}>Guide not found.</p>
      </main>
    );
  }

  const isRTL = RTL_LEGAL_LANGS.has(legalLang);
  const whoQualArr = pickArr(entry.whoQualifies, legalLang);
  const rightsArr = pickArr(entry.yourRights, legalLang);
  const optionsArr = pickArr(entry.legalOptions, legalLang);
  const relIds = (entry.relatedIds || []).filter((rid) => LEGAL_ENTRIES_BY_ID[rid]);
  const catMeta = CATEGORY_META[entry.category] || { label: entry.category };

  return (
    <main dir={isRTL ? "rtl" : "ltr"} style={{ padding: "0 20px 40px", maxWidth: 900, margin: "0 auto" }}>
      <button onClick={onBack} style={{ background: "none", border: "none", cursor: "pointer", fontSize: 14, color: C.stone, padding: "16px 0", fontFamily: "inherit" }}>← Back to {catMeta.label}</button>

      <LanguagePicker legalLang={legalLang} setLegalLang={setLegalLang} compact />

      <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 10, flexWrap: "wrap" }}>
        <span style={{ fontSize: 10, fontWeight: 700, color: C.forest, background: C.sage, padding: "3px 8px", borderRadius: 6, textTransform: "uppercase", letterSpacing: 0.5 }}>{entry.tier}</span>
        <span style={{ fontSize: 11, color: C.dust, textTransform: "uppercase", letterSpacing: 0.5 }}>
          {catMeta.label}{entry.jurisdiction ? " · " + entry.jurisdiction.toUpperCase() : ""}
        </span>
      </div>

      <h1 style={{ fontFamily: SERIF, fontSize: 32, fontWeight: 400, marginBottom: 14, color: C.bark, lineHeight: 1.25 }}>
        {pickText(entry.title, legalLang)}
      </h1>

      <p style={{ fontSize: 17, color: C.stone, lineHeight: 1.6, marginBottom: 20, fontWeight: 500 }}>
        {pickText(entry.summary, legalLang)}
      </p>

      {entry.reviewedBy && (
        <div style={{
          marginBottom: 24,
          padding: "14px 18px",
          background: C.sage,
          borderRadius: 12,
          border: "1px solid #c8e6c9",
          fontSize: 13,
          lineHeight: 1.55,
        }}>
          <div style={{ color: C.forest, fontWeight: 600, marginBottom: 6, display: "flex", alignItems: "center", gap: 6 }}>
            <span style={{ fontSize: 14 }}>✓</span>
            <span>Reviewed by {entry.reviewedBy}</span>
          </div>
          <div style={{ color: C.stone, fontStyle: "italic" }}>
            This guide is general legal information, not legal advice for your specific situation.
          </div>
        </div>
      )}

      {whoQualArr.length > 0 && (
        <section style={{ marginBottom: 26 }}>
          <h2 style={{ fontFamily: SERIF, fontSize: 22, fontWeight: 400, marginBottom: 12, color: C.bark }}>Who qualifies</h2>
          <ul style={{ margin: 0, paddingLeft: isRTL ? 0 : 22, paddingRight: isRTL ? 22 : 0, fontSize: 15, color: C.bark, lineHeight: 1.7 }}>
            {whoQualArr.map((item, i) => <li key={i} style={{ marginBottom: 8 }}>{item}</li>)}
          </ul>
        </section>
      )}

      {entry.whatItMeans && (
        <section style={{ marginBottom: 26 }}>
          <h2 style={{ fontFamily: SERIF, fontSize: 22, fontWeight: 400, marginBottom: 12, color: C.bark }}>What it means</h2>
          <p style={{ fontSize: 15, color: C.bark, lineHeight: 1.8, margin: 0, whiteSpace: "pre-wrap" }}>
            {pickText(entry.whatItMeans, legalLang)}
          </p>
        </section>
      )}

      {rightsArr.length > 0 && (
        <section style={{ marginBottom: 26, padding: "18px 22px", background: C.sage, borderRadius: 14, border: "1px solid #c8e6c9" }}>
          <h2 style={{ fontFamily: SERIF, fontSize: 22, fontWeight: 400, marginBottom: 12, color: C.forest }}>Your rights</h2>
          <ul style={{ margin: 0, paddingLeft: isRTL ? 0 : 22, paddingRight: isRTL ? 22 : 0, fontSize: 15, color: C.bark, lineHeight: 1.7 }}>
            {rightsArr.map((item, i) => <li key={i} style={{ marginBottom: 8 }}>{item}</li>)}
          </ul>
        </section>
      )}

      {optionsArr.length > 0 && (
        <section style={{ marginBottom: 26 }}>
          <h2 style={{ fontFamily: SERIF, fontSize: 22, fontWeight: 400, marginBottom: 12, color: C.bark }}>Legal options</h2>
          <ul style={{ margin: 0, paddingLeft: isRTL ? 0 : 22, paddingRight: isRTL ? 22 : 0, fontSize: 15, color: C.bark, lineHeight: 1.7 }}>
            {optionsArr.map((item, i) => <li key={i} style={{ marginBottom: 10 }}>{item}</li>)}
          </ul>
        </section>
      )}

      {entry.example && (
        <section style={{ marginBottom: 26, padding: "18px 22px", background: C.amberLight, borderRadius: 14, border: "1px solid #f0dab0" }}>
          <h2 style={{ fontFamily: SERIF, fontSize: 20, fontWeight: 400, marginBottom: 10, color: C.bark }}>Example</h2>
          <p style={{ fontSize: 14, color: C.stone, lineHeight: 1.7, margin: 0, fontStyle: "italic" }}>
            {pickText(entry.example, legalLang)}
          </p>
        </section>
      )}

      {entry.counsel && entry.counsel.length > 0 && (
        <section style={{ marginBottom: 26 }}>
          <h2 style={{ fontFamily: SERIF, fontSize: 22, fontWeight: 400, marginBottom: 12, color: C.bark }}>Get free legal help</h2>
          <div style={{ display: "grid", gap: 12 }}>
            {entry.counsel.map((c, i) => (
              <div key={i} style={{ padding: "14px 18px", background: C.white, borderRadius: 12, border: "1px solid " + C.border }}>
                <div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 6 }}>
                  <span style={{ fontSize: 9, fontWeight: 700, color: C.forest, background: C.sage, padding: "2px 7px", borderRadius: 5, textTransform: "uppercase", letterSpacing: 0.5 }}>{c.type || "free"}</span>
                  {c.verified && <span style={{ fontSize: 10, color: C.forest }}>✓ verified</span>}
                </div>
                <div style={{ fontSize: 15, fontWeight: 600, color: C.bark, marginBottom: 4 }}>{c.name}</div>
                {c.focus && <div style={{ fontSize: 13, color: C.stone, marginBottom: 4 }}>{c.focus}</div>}
                {c.qualifier && <div style={{ fontSize: 12, color: C.dust, marginBottom: 8, fontStyle: "italic" }}>{c.qualifier}</div>}
                <div style={{ display: "flex", gap: 12, flexWrap: "wrap", alignItems: "center" }}>
                  {c.phone && (
                    <a href={"tel:" + c.phone.replace(/[^0-9+]/g, "")} style={{ background: C.forest, color: C.white, padding: "8px 16px", borderRadius: 8, fontSize: 14, fontWeight: 600, textDecoration: "none" }}>
                      📞 {c.phone}
                    </a>
                  )}
                  {c.url && (
                    <a href={c.url} target="_blank" rel="noopener noreferrer" style={{ color: C.forest, fontSize: 13, textDecoration: "underline" }}>
                      website ↗
                    </a>
                  )}
                </div>
              </div>
            ))}
          </div>
        </section>
      )}

      {relIds.length > 0 && (
        <section style={{ marginBottom: 26 }}>
          <h2 style={{ fontFamily: SERIF, fontSize: 20, fontWeight: 400, marginBottom: 12, color: C.bark }}>Related guides</h2>
          <div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}>
            {relIds.map((rid) => (
              <button
                key={rid}
                onClick={() => onOpenEntry(rid)}
                style={{ background: C.white, border: "1px solid " + C.border, borderRadius: 8, padding: "8px 14px", cursor: "pointer", fontFamily: "inherit", fontSize: 13, color: C.forest }}
              >
                {pickText(LEGAL_ENTRIES_BY_ID[rid].title, legalLang)}
              </button>
            ))}
          </div>
        </section>
      )}

      {entry.sources && entry.sources.length > 0 && (
        <section style={{ marginBottom: 20, paddingTop: 20, borderTop: "1px solid " + C.border }}>
          <div style={{ fontSize: 12, fontWeight: 600, color: C.stone, marginBottom: 8, textTransform: "uppercase", letterSpacing: 0.5 }}>Sources & citations</div>
          <ul style={{ margin: 0, paddingLeft: isRTL ? 0 : 18, paddingRight: isRTL ? 18 : 0, fontSize: 12, color: C.dust, lineHeight: 1.6 }}>
            {entry.sources.map((s, i) => (
              <li key={i}>
                <a href={s} target="_blank" rel="noopener noreferrer" style={{ color: C.dust, wordBreak: "break-all" }}>{s}</a>
              </li>
            ))}
          </ul>
        </section>
      )}

      {GLOSSARY_TERMS_BY_CATEGORY[entry.category] && GLOSSARY_TERMS_BY_CATEGORY[entry.category].length > 0 && (
        <a
          href={"/glossary/category/" + entry.category}
          style={{
            display: "flex", alignItems: "center", gap: 10,
            marginTop: 20, padding: "12px 16px",
            background: "#ede7f6", border: "1px solid #5e35b1",
            borderRadius: 10, color: "#4527a0",
            fontSize: 14, fontWeight: 600, textDecoration: "none",
          }}
        >
          <span style={{ fontSize: 20 }}>📖</span>
          <span style={{ flex: 1 }}>Common phrases in this topic — {GLOSSARY_TERMS_BY_CATEGORY[entry.category].length} words explained</span>
          <span>→</span>
        </a>
      )}
      <div style={{ fontSize: 11, color: C.dust, marginTop: 14, paddingTop: 12, borderTop: "1px solid " + C.border }}>
        Last audited: {entry.lastAudited || "unknown"} · Entry ID: {entry.id}
      </div>

      <div style={{ marginTop: 20, padding: "14px 18px", background: C.amberLight, borderRadius: 12, border: "1px solid #f0dab0", fontSize: 12, color: C.stone, lineHeight: 1.6 }}>
        ⚠️ <strong>Not legal advice.</strong> This guide explains your general rights. Laws change. For your specific situation, contact one of the free legal aid organizations listed above.
      </div>
    </main>
  );
}
